build_clean_manifest:
  project_root: .
  espeak_lang: en

noise:
  seed: 42

predict:
  model_name: facebook/wav2vec2-lv-60-espeak-cv-ft
  device: auto
  target_sr: 16000
  espeak_library: C:/Program Files/eSpeak NG/libespeak-ng.dll
